name: Thorntail - Config Map
description: Simple HTTP endpoint where the Thorntail application uses OpenShift ConfigMap to retrieve application parameters.
source:
  git:
    url: https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-configmap
    ref: master
environment:
  staging:
    source:
      git:
        ref: '12'
  production:
    source:
      git:
        ref: '12'
