name: Vert.x - HTTP & Config Map
description: Simple HTTP endpoint where the Vert.x application uses OpenShift ConfigMap to get the application parameters.
source:
  git:
    url: https://github.com/openshift-vertx-examples/vertx-configmap-example
    ref: master
environment:
  staging:
    source:
      git:
        ref: v36
  production:
    source:
      git:
        ref: v36
