source:
  git:
    ref: master
metadata:
  version:
    name: 1.5.8.RELEASE (Community)
environment:
  staging:
    source:
      git:
        ref: v13
  production:
    source:
      git:
        ref: v13
