source:
  git:
    url: https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-configmap
    ref: master
metadata:
  version:
    name: 2017.10.0 (Community)
environment:
  staging:
    source:
      git:
        ref: '10'
  production:
    source:
      git:
        ref: '10'
