source:
  git:
    url: https://github.com/bucharest-gold/nodejs-configmap
    ref: master
metadata:
  version:
    name: 8.x (Community)
environment:
  staging:
    source:
      git:
        ref: v1.1.2
  production:
    source:
      git:
        ref: v1.1.2
